{{- if .Values.global.shoparazziNamespace  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: pod-reader
  namespace: {{ .Values.global.shoparazziNamespace }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-heimdall
subjects:
- kind: ServiceAccount
  name: {{ include "heimdall.serviceAccountName" . }}
  namespace: {{ .Values.global.shoparazziNamespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ""

{{- end }}