name: 'Deploy'
on: [deployment]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v1'

      - name: Set Test Kubeconfig
        if: github.event.deployment.environment == 'test'
        run: |
          echo "KUBECONFIG_FILE<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.TEST_KUBECONFIG }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set Production Kubeconfig
        if: github.event.deployment.environment == 'production'
        run: |
          echo "KUBECONFIG_FILE<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.PRODUCTION_KUBECONFIG }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 'Deploy Shoparazzi'
        # Parameters are pulled directly from the GitHub deployment event so the
        # configuration for the job here is very minimal.
        uses: 'deliverybot/helm@master'
        with:
          token: '${{ github.token }}'
          secrets: '${{ toJSON(secrets) }}'
          version: '${{ github.sha }}'
          chart: './charts/shoparazzi'
