name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

  push:
    branches: [master]

env:
  HELM_VERSION: v3.6.3

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run yamllint
        run: yamllint --config-file .yamllint .
      - name: Run helm lint
        run: helm lint charts/*

  test:
    runs-on: ubuntu-20.04
    # container: quay.io/helmpack/chart-testing

    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      # https://github.com/helm/chart-testing/blob/main/doc/ct_list-changed.md
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yml

      # TODO: FIXME: chart-testing action fails because of imagePullSecrets
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.2.0
      #   if: steps.list-changed.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   run: ct install --config ct.yml
